<#
.SYNOPSIS
  Build the runnable distribution: dist/app.jar + dist/lib/*.jar + launchers.

.DESCRIPTION
  Why not a shaded fat jar: the offline repository has no maven-shade-plugin (nor its
  dependencies), so packaging is done here:
    1) mvn -o -DskipTests=true package          -> target/app.jar (classes + resources only)
    2) resolve dependencies offline             -> scripts/resolve-classpath.ps1
    3) copy every runtime jar into dist/lib/    -> started via `java -cp "app.jar;lib/*"`
  The manifest generated by maven-jar-plugin already points at lib/ for the classpath,
  so `java -jar dist/app.jar` also works.

  NOTE: keep this file ASCII-only (Windows PowerShell 5.1 reads .ps1 as ANSI).
#>
[CmdletBinding()]
param(
    [string]$OutDir = 'dist'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Push-Location $root
try {
    Write-Host '[1/4] building target/app.jar ...' -ForegroundColor Cyan
    & mvn -o -s "$root\.m2settings.xml" -q "-DskipTests=true" package
    if ($LASTEXITCODE -ne 0) { throw "mvn package failed (exit=$LASTEXITCODE)" }

    $jar = Join-Path $root 'target\app.jar'
    if (-not (Test-Path $jar)) { throw "target/app.jar not found" }

    Write-Host '[2/4] resolving runtime classpath ...' -ForegroundColor Cyan
    $allJars = & "$PSScriptRoot\resolve-classpath.ps1"
    $runtimeJars = @($allJars | Where-Object { $_ -like '*\*.jar' -and $_ -notmatch 'junit|assertj|opentest4j|apiguardian|jspecify|mockito|byte-buddy|json-path|jsonassert|xmlunit|awaitility|spring-boot-test|spring-test' })
    if ($runtimeJars.Count -eq 0) { throw 'runtime classpath is empty' }

    Write-Host '[3/4] assembling dist ...' -ForegroundColor Cyan
    $dist = Join-Path $root $OutDir
    if (Test-Path $dist) { Remove-Item $dist -Recurse -Force }
    $libDir = Join-Path $dist 'lib'
    New-Item -ItemType Directory -Path $libDir -Force | Out-Null
    Copy-Item $jar (Join-Path $dist 'app.jar') -Force
    foreach ($dependency in $runtimeJars) {
        Copy-Item $dependency $libDir -Force
    }

    # launcher scripts (ASCII only, CRLF)
    $appCmd = @(
        '@echo off',
        'rem AI interview coach launcher. Usage: app.cmd [--server.port=8090]',
        'setlocal',
        'set "APP_HOME=%~dp0"',
        'set "JAVA_OPTS=%JAVA_OPTS% -Dfile.encoding=UTF-8 -Dapp.home=%APP_HOME%"',
        'java %JAVA_OPTS% -jar "%APP_HOME%app.jar" %*',
        'exit /b %ERRORLEVEL%'
    ) -join "`r`n"
    Set-Content -Path (Join-Path $dist 'app.cmd') -Value $appCmd -Encoding ascii

    $appSh = @(
        '#!/usr/bin/env sh',
        '# AI interview coach launcher. Usage: ./app.sh [--server.port=8090]',
        'APP_HOME=$(cd "$(dirname "$0")" && pwd)',
        'exec java $JAVA_OPTS -Dfile.encoding=UTF-8 -Dapp.home="$APP_HOME" -jar "$APP_HOME/app.jar" "$@"'
    ) -join "`n"
    Set-Content -Path (Join-Path $dist 'app.sh') -Value $appSh -Encoding ascii

    Write-Host '[4/4] smoke check: jar contents and size ...' -ForegroundColor Cyan
    $size = [math]::Round(((Get-ChildItem $dist -Recurse -File | Measure-Object Length -Sum).Sum / 1MB), 1)
    $libCount = (Get-ChildItem $libDir -Filter *.jar).Count
    Write-Host ("dist ready: {0} ({1} jars in lib, {2} MB)" -f $dist, $libCount, $size) -ForegroundColor Green
    Write-Host ("start with: {0}\app.cmd" -f $dist) -ForegroundColor Green
}
finally {
    Pop-Location
}
